static const char RELEASE_UPDATE_JS[] =
"(function(){\n"
" const box=document.getElementById('release-updates'); if(!box)return;\n"
" box.innerHTML='<h3>Official release updates</h3><label><input type=\"checkbox\" id=\"release-enabled\"> Check for updates every six hours</label><p id=\"release-status\" role=\"status\"></p><p id=\"release-error\" role=\"alert\"></p><a id=\"release-notes\" target=\"_blank\" rel=\"noopener noreferrer\" hidden>Release notes</a><br><button type=\"button\" id=\"release-check\">Check now</button> <button type=\"button\" id=\"release-install\" hidden>Update</button> <button type=\"button\" id=\"release-later\" hidden>Later</button> <button type=\"button\" id=\"release-skip\" hidden>Skip this version</button>';\n"
" let current=null,busy=false;\n"
" const el=id=>document.getElementById('release-'+id);\n"
" async function refresh(){try{const r=await fetch('/updates',{cache:'no-store'});if(!r.ok)throw Error('Status unavailable');current=await r.json();el('enabled').checked=current.checks_enabled;el('status').textContent='Installed '+current.current_version+'. '+(current.available?(current.prompt?'Update available: ':'Available in settings: ')+current.tag+'. ':'')+current.stage+(current.bytes?' \u2014 '+Math.floor(current.bytes/1024)+' / '+Math.floor(current.size/1024)+' KB':'')+(current.checked_at?' \u2022 Checked '+new Date(current.checked_at*1000).toLocaleString():'');el('error').textContent=current.error||'';el('notes').hidden=!current.release_url;el('notes').href=current.release_url||'#';el('install').hidden=!current.available;el('later').hidden=el('skip').hidden=!current.prompt;for(const b of box.querySelectorAll('button,input'))b.disabled=busy||['checking','downloading','restarting'].includes(current.stage);}catch(e){el('error').textContent='Controller unreachable; update outcome is not yet confirmed. Reconnect to check its version.';}}\n"
" async function action(op,extra){if(busy)return;if(op==='install'&&!confirm('Install '+current.tag+'? The controller will restart and briefly interrupt outlet control.'))return;busy=true;try{const r=await fetch('/updates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({v:1,id:Date.now()+'-'+Math.random(),op,tag:current?.tag||'',confirmed:op==='install',...extra})});if(!r.ok)throw Error('Request rejected or controller busy. Try again.');}catch(e){el('error').textContent=e.message;}finally{busy=false;}}\n"
" for(const op of ['check','install','later','skip'])el(op).onclick=()=>action(op);\n"
" el('enabled').onchange=()=>action('settings',{enabled:el('enabled').checked});\n"
" refresh();setInterval(refresh,2000);\n"
"})();\n";
